services:
  db:
    image: postgres:15-alpine 
    container_name: postgres_container
    restart: always
    environment:
      POSTGRES_DB: ${DATABASE_NAME:-StoreApp}
      POSTGRES_USER: ${DATABASE_USER:-postgres}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD:-1234}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  web:
    build: .
    container_name: django_container
    restart: always
    depends_on:
      db:
        condition: service_healthy
    environment:
      DATABASE_NAME: ${DATABASE_NAME:-StoreApp}
      DATABASE_USER: ${DATABASE_USER:-postgres}
      DATABASE_PASSWORD: ${DATABASE_PASSWORD:-1234}
      DATABASE_HOST: db
      DATABASE_PORT: 5432
      DEBUG: ${DEBUG:-1}
      DJANGO_SETTINGS_MODULE: StoreApp.settings
      DJANGO_SUPERUSER_USERNAME: ${DJANGO_SUPERUSER_USERNAME:-admin}
      DJANGO_SUPERUSER_EMAIL: ${DJANGO_SUPERUSER_EMAIL:-admin@example.com}
      DJANGO_SUPERUSER_PASSWORD: ${DJANGO_SUPERUSER_PASSWORD:-admin}
      DJANGO_ENV: ${DJANGO_ENV:-development}
    ports:
      - "8000:8000"
    volumes:
      - .:/app
      - static_volume:/app/staticfiles
      - media_volume:/app/mediafiles
    command: ["/app/entrypoint.sh"]

volumes:
  postgres_data:
  static_volume:
  media_volume: