# Generated by Django 6.0.6 on 2026-06-08 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='name',
        ),
        migrations.AlterField(
            model_name='user',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Активен ли пользователь'),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_login',
            field=models.DateTimeField(auto_now=True, verbose_name='Время последнего входа'),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone_number',
            field=models.CharField(max_length=12, verbose_name='Номер телефона пользователя'),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_info',
            field=models.TextField(max_length=255, null=True, verbose_name='Дополнительная информация о пользователе'),
        ),
    ]
